ChartValues:
  basic:
    image_registry: compute-nest-registry.cn-hangzhou.cr.aliyuncs.com/public
HelmChartPath: helm
RuntimeType: Kubernetes
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: aliyun-computenest/quickstart-volcano
RegionId: cn-hangzhou
OutputType: HelmNotes
Owner: yehanyh
Branch: main
Platform: github
